{% set version = "0.2.0" %}

{% set PYTHON = PYTHON | default("$PYTHON") %} 

package:
  name: doitoml
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/doitoml/doitoml-{{ version }}.tar.gz
  sha256: d81bc676ba42ef5558116accb5b35c08a40b679c3251f6d99484b0b6fa6f79f8

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - flit-core >=3.9.0,<4
    - pip <24
    - python {{ python_min }}
  run:
    - doit >=0.36
    - python >={{ python_min }}
    - tomli
    - typing_extensions
test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - doitoml
  commands:
    - pip check

outputs:
  - name: doitoml

  - name: doitoml-with-jinja2
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("doitoml", max_pin="x.x.x") }}
        - jinja2 >=3
    test:
      imports:
        - doitoml.templaters.jinja2
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: doitoml-with-json-e
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("doitoml", max_pin="x.x.x") }}
        - json-e >=4
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - doitoml.templaters.jsone
      commands:
        - pip check

  - name: doitoml-with-jsonschema
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage("doitoml", max_pin="x.x.x") }}
        - jsonschema >=4
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - doitoml.schema.validator
      commands:
        - pip check

  - name: doitoml-with-yaml
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage("doitoml", max_pin="x.x.x") }}
        - pyyaml >=5
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - doitoml.sources.yaml._yaml
      commands:
        - pip check

  - name: doitoml-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("doitoml", max_pin="x.x.x") }}
        - {{ pin_subpackage("doitoml-with-jinja2", max_pin="x.x.x") }}
        - {{ pin_subpackage("doitoml-with-json-e", max_pin="x.x.x") }}
        - {{ pin_subpackage("doitoml-with-jsonschema", max_pin="x.x.x") }}
        - {{ pin_subpackage("doitoml-with-yaml", max_pin="x.x.x") }}
    test:
      source_files:
        - test
        - pyproject.toml
        - examples
      requires:
        - pip
        - pytest
        - pytest-console-scripts
        - pytest-cov
        - pytest-html
        - pytest-json-report
        - pytest-xdist
        - python {{ python_min }}
        - python-build
        - tomli-w
      imports:
        - doitoml
      commands:
        - pip check
        - pytest -vv --cov=doitoml --cov=branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not self" --cov-fail-under=90

about:
  summary: Load declarative tasks for doit from TOML, JSON, YAML, and other files.
  home: https://github.com/deathbeds/doitoml
  license: BSD-3-Clause
  license_file: LICENSE.txt
  doc_url: https://doitoml.rtfd.io

extra:
  recipe-maintainers:
    - bollwyvl
